name = "govd"
main = "src/index.ts"          # <-- cambia se il tuo entry point è diverso (es. dist/index.js)
compatibility_date = "2026-06-10"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "BOT_KV"
id = "fa61343228ef41f094d3c00e5023db6f"

[vars]
BOT_USERNAME = "govd_bot"
OWNER_ID = "123456789"
