import i18next from 'i18next';

type LangCode = 'en' | 'it' | 'de' | 'es' | 'fr' | 'pt' | 'ru' | 'zh' | 'ar' | 'ja' | 'ko';
type Messages = Record<string, Partial<Record<LangCode, string>>>;

const messages: Messages = {
  Language: {
    en: 'english', it: 'italiano', de: 'deutsch', es: 'español',
    fr: 'français', pt: 'português', ru: 'русский', zh: '中文',
    ar: 'العربية', ja: '日本語', ko: '한국어',
  },
  StartMessage: {
    en: 'welcome {{Name}} to govd, an open-source telegram bot for downloading content from various social platforms',
    it: 'benvenuto {{Name}} su govd, un bot telegram open-source per scaricare contenuti da varie piattaforme social',
    de: 'willkommen {{Name}} bei govd, einem Open-Source-Telegram-Bot zum Herunterladen von Inhalten aus verschiedenen sozialen Plattformen',
    es: 'bienvenido {{Name}} a govd, un bot de Telegram de código abierto para descargar contenido de varias plataformas sociales',
    fr: 'bienvenue {{Name}} sur govd, un bot Telegram open-source pour télécharger du contenu de diverses plateformes sociales',
    pt: 'bem-vindo {{Name}} ao govd, um bot de Telegram de código aberto para baixar conteúdo de várias plataformas sociais',
    ru: 'добро пожаловать {{Name}} в govd, телеграм-бот с открытым кодом для загрузки контента с различных социальных платформ',
    zh: '欢迎 {{Name}} 使用 govd，这是一个开源的 Telegram 机器人，用于从各种社交平台下载内容',
    ar: 'مرحباً {{Name}} في govd، بوت تيليجرام مفتوح المصدر لتنزيل المحتوى من منصات التواصل الاجتماعي المختلفة',
    ja: '{{Name}} さん、govd へようこそ。様々なソーシャルプラットフォームからコンテンツをダウンロードするオープンソースの Telegram ボットです',
    ko: '{{Name}} 님, govd에 오신 것을 환영합니다. 다양한 소셜 플랫폼에서 콘텐츠를 다운로드하는 오픈소스 텔레그램 봇입니다',
  },
  AddButton: {
    en: 'add to a group', it: 'aggiungi a un gruppo', de: 'zu einer Gruppe hinzufügen',
    es: 'añadir a un grupo', fr: 'ajouter à un groupe', pt: 'adicionar a um grupo',
    ru: 'добавить в группу', zh: '添加到群组', ar: 'أضف إلى مجموعة',
    ja: 'グループに追加', ko: '그룹에 추가',
  },
  ErrorMessage: {
    en: 'an error occurred, please try again later',
    it: 'si è verificato un errore, riprova più tardi',
    de: 'ein Fehler ist aufgetreten, bitte versuche es später erneut',
    es: 'ocurrió un error, por favor inténtalo más tarde',
    fr: "une erreur s'est produite, veuillez réessayer plus tard",
    pt: 'ocorreu um erro, por favor tente novamente mais tarde',
    ru: 'произошла ошибка, пожалуйста, повторите попытку позже',
    zh: '发生错误，请稍后再试', ar: 'حدث خطأ، يرجى المحاولة مرة أخرى لاحقاً',
    ja: 'エラーが発生しました。後でもう一度お試しください',
    ko: '오류가 발생했습니다. 나중에 다시 시도해 주세요',
  },
  AddedToGroupMessage: {
    en: 'thank you for adding me! use /settings command to configure the bot for this group',
    it: 'grazie per avermi aggiunto! usa il comando /settings per configurare il bot per questo gruppo',
    de: 'danke fürs Hinzufügen! Nutze den /settings-Befehl, um den Bot für diese Gruppe zu konfigurieren',
    es: '¡gracias por añadirme! usa el comando /settings para configurar el bot en este grupo',
    fr: "merci de m'avoir ajouté ! utilise la commande /settings pour configurer le bot dans ce groupe",
    pt: 'obrigado por me adicionar! use o comando /settings para configurar o bot neste grupo',
    ru: 'спасибо за добавление! используйте команду /settings для настройки бота в этой группе',
    zh: '感谢您添加我！请使用 /settings 命令为此群组配置机器人',
    ar: 'شكراً لإضافتي! استخدم أمر /settings لتهيئة البوت لهذه المجموعة',
    ja: '追加していただきありがとうございます！/settings コマンドを使って、このグループのボットを設定してください',
    ko: '추가해 주셔서 감사합니다! /settings 명령어를 사용하여 이 그룹의 봇을 설정하세요',
  },
  SettingsButton: {
    en: 'settings', it: 'impostazioni', de: 'einstellungen', es: 'ajustes',
    fr: 'paramètres', pt: 'configurações', ru: 'настройки', zh: '设置',
    ar: 'الإعدادات', ja: '設定', ko: '설정',
  },
  LanguageButton: {
    en: 'language', it: 'lingua', de: 'sprache', es: 'idioma',
    fr: 'langue', pt: 'idioma', ru: 'язык', zh: '语言',
    ar: 'اللغة', ja: '言語', ko: '언어',
  },
  PrivateSettingsMessage: {
    en: 'use the buttons below to change your personal bot settings',
    it: 'usa i pulsanti qui sotto per modificare le tue impostazioni personali del bot',
    de: 'nutze die Schaltflächen unten, um deine persönlichen Bot-Einstellungen zu ändern',
    es: 'usa los botones de abajo para cambiar tu configuración personal del bot',
    fr: 'utilise les boutons ci-dessous pour modifier tes paramètres personnels du bot',
    pt: 'use os botões abaixo para alterar suas configurações pessoais do bot',
    ru: 'используйте кнопки ниже, чтобы изменить личные настройки бота',
    zh: '使用下方按钮更改您的个人机器人设置', ar: 'استخدم الأزرار أدناه لتغيير إعداداتك الشخصية للبوت',
    ja: '以下のボタンを使って個人のボット設定を変更してください',
    ko: '아래 버튼을 사용하여 개인 봇 설정을 변경하세요',
  },
  GroupSettingsMessage: {
    en: "use the buttons below to change this group's bot settings",
    it: 'usa i pulsanti qui sotto per modificare le impostazioni del bot per questo gruppo',
    de: 'nutze die Schaltflächen unten, um die Bot-Einstellungen für diese Gruppe zu ändern',
    es: 'usa los botones de abajo para cambiar la configuración del bot en este grupo',
    fr: 'utilise les boutons ci-dessous pour modifier les paramètres du bot pour ce groupe',
    pt: 'use os botões abaixo para alterar as configurações do bot neste grupo',
    ru: 'используйте кнопки ниже, чтобы изменить настройки бота для этой группы',
    zh: '使用下方按钮更改此群组的机器人设置', ar: 'استخدم الأزرار أدناه لتغيير إعدادات البوت لهذه المجموعة',
    ja: '以下のボタンを使ってこのグループのボット設定を変更してください',
    ko: '아래 버튼을 사용하여 이 그룹의 봇 설정을 변경하세요',
  },
  BackButton: {
    en: 'back', it: 'indietro', de: 'zurück', es: 'atrás', fr: 'retour',
    pt: 'voltar', ru: 'назад', zh: '返回', ar: 'رجوع', ja: '戻る', ko: '뒤로',
  },
  SelectLanguageMessage: {
    en: 'select your preferred language', it: 'seleziona la tua lingua preferita',
    de: 'wähle deine bevorzugte Sprache', es: 'selecciona tu idioma preferido',
    fr: 'sélectionne ta langue préférée', pt: 'selecione seu idioma preferido',
    ru: 'выберите предпочитаемый язык', zh: '选择您偏好的语言',
    ar: 'اختر لغتك المفضلة', ja: 'お好みの言語を選択してください',
    ko: '선호하는 언어를 선택하세요',
  },
  CaptionsSettingsMessage: {
    en: 'when enabled, adds original description to downloaded content, if available',
    it: 'se abilitato, aggiunge la descrizione originale ai contenuti scaricati, se disponibile',
    de: 'wenn aktiviert, wird die Originalbeschreibung zu heruntergeladenen Inhalten hinzugefügt, sofern verfügbar',
    es: 'cuando está habilitado, añade la descripción original al contenido descargado, si está disponible',
    fr: "si activé, ajoute la description originale au contenu téléchargé, si disponible",
    pt: 'quando ativado, adiciona a descrição original ao conteúdo baixado, se disponível',
    ru: 'если включено, добавляет оригинальное описание к загруженному контенту, если доступно',
    zh: '启用后，如果可用，将在下载的内容中添加原始描述',
    ar: 'عند التفعيل، يضيف الوصف الأصلي للمحتوى المنزّل، إذا كان متاحاً',
    ja: '有効にすると、ダウンロードしたコンテンツに元の説明が追加されます（利用可能な場合）',
    ko: '활성화하면 다운로드한 콘텐츠에 원본 설명이 추가됩니다(사용 가능한 경우)',
  },
  NsfwSettingsMessage: {
    en: 'when enabled, allows downloading nsfw content in this chat',
    it: 'se abilitato, consente il download di contenuti nsfw in questa chat',
    de: 'wenn aktiviert, erlaubt das Herunterladen von NSFW-Inhalten in diesem Chat',
    es: 'cuando está habilitado, permite descargar contenido nsfw en este chat',
    fr: 'si activé, permet de télécharger du contenu nsfw dans ce chat',
    pt: 'quando ativado, permite baixar conteúdo nsfw neste chat',
    ru: 'если включено, разрешает загрузку nsfw-контента в этом чате',
    zh: '启用后，允许在此聊天中下载 nsfw 内容',
    ar: 'عند التفعيل، يسمح بتنزيل المحتوى الإباحي في هذه المحادثة',
    ja: '有効にすると、このチャットで NSFW コンテンツのダウンロードが許可されます',
    ko: '활성화하면 이 채팅에서 nsfw 콘텐츠 다운로드가 허용됩니다',
  },
  SilentModeSettingsMessage: {
    en: 'when enabled, the bot will not send error messages',
    it: 'se abilitato, il bot non invierà messaggi di errore',
    de: 'wenn aktiviert, sendet der Bot keine Fehlermeldungen',
    es: 'cuando está habilitado, el bot no enviará mensajes de error',
    fr: "si activé, le bot n'enverra pas de messages d'erreur",
    pt: 'quando ativado, o bot não enviará mensagens de erro',
    ru: 'если включено, бот не будет отправлять сообщения об ошибках',
    zh: '启用后，机器人将不发送错误消息', ar: 'عند التفعيل، لن يرسل البوت رسائل الخطأ',
    ja: '有効にすると、ボットはエラーメッセージを送信しません',
    ko: '활성화하면 봇이 오류 메시지를 보내지 않습니다',
  },
  MediaAlbumSettingsMessage: {
    en: 'select maximum number of files allowed in a single media album',
    it: 'seleziona il numero massimo di file consentiti in un singolo album multimediale',
    de: 'wähle die maximale Anzahl von Dateien in einem einzelnen Medienalbum',
    es: 'selecciona el número máximo de archivos permitidos en un álbum multimedia',
    fr: "sélectionne le nombre maximum de fichiers autorisés dans un seul album multimédia",
    pt: 'selecione o número máximo de arquivos permitidos em um único álbum de mídia',
    ru: 'выберите максимальное количество файлов в одном медиаальбоме',
    zh: '选择单个媒体相册中允许的最大文件数',
    ar: 'اختر الحد الأقصى لعدد الملفات المسموح بها في ألبوم وسائط واحد',
    ja: '1つのメディアアルバムで許可されるファイルの最大数を選択してください',
    ko: '단일 미디어 앨범에 허용되는 최대 파일 수를 선택하세요',
  },
  InlineLoadingMessage: {
    en: 'loading... please wait', it: 'caricamento... attendere',
    de: 'wird geladen... bitte warten', es: 'cargando... por favor espera',
    fr: 'chargement... veuillez patienter', pt: 'carregando... por favor aguarde',
    ru: 'загрузка... пожалуйста, подождите', zh: '加载中... 请稍候',
    ar: 'جارٍ التحميل... يرجى الانتظار', ja: '読み込み中... お待ちください',
    ko: '로딩 중... 잠시 기다려 주세요',
  },
  InlineShareMessage: {
    en: 'share this media', it: 'condividi questo media', de: 'dieses Medium teilen',
    es: 'compartir este contenido', fr: 'partager ce média', pt: 'compartilhar esta mídia',
    ru: 'поделиться этим медиа', zh: '分享此媒体', ar: 'مشاركة هذه الوسائط',
    ja: 'このメディアを共有', ko: '이 미디어 공유',
  },
  NoPermission: {
    en: "you don't have permissions to perform this action",
    it: 'non hai i permessi per eseguire questa azione',
    de: 'du hast keine Berechtigung, diese Aktion durchzuführen',
    es: 'no tienes permisos para realizar esta acción',
    fr: "tu n'as pas les permissions pour effectuer cette action",
    pt: 'você não tem permissões para realizar esta ação',
    ru: 'у вас нет прав для выполнения этого действия',
    zh: '您没有权限执行此操作', ar: 'ليس لديك صلاحيات لتنفيذ هذا الإجراء',
    ja: 'このアクションを実行する権限がありません',
    ko: '이 작업을 수행할 권한이 없습니다',
  },
  CloseButton: {
    en: 'close', it: 'chiudi', de: 'schließen', es: 'cerrar', fr: 'fermer',
    pt: 'fechar', ru: 'закрыть', zh: '关闭', ar: 'إغلاق', ja: '閉じる', ko: '닫기',
  },
  MediaAlbumButton: {
    en: 'media album', it: 'album multimediale', de: 'medienalbum', es: 'álbum multimedia',
    fr: 'album multimédia', pt: 'álbum de mídia', ru: 'медиаальбом', zh: '媒体相册',
    ar: 'ألبوم الوسائط', ja: 'メディアアルバム', ko: '미디어 앨범',
  },
  SilentModeButton: {
    en: 'silent mode', it: 'modalità silenziosa', de: 'stummschaltung', es: 'modo silencioso',
    fr: 'mode silencieux', pt: 'modo silencioso', ru: 'тихий режим', zh: '静音模式',
    ar: 'الوضع الصامت', ja: 'サイレントモード', ko: '무음 모드',
  },
  CaptionsButton: {
    en: 'captions', it: 'didascalie', de: 'untertitel', es: 'subtítulos',
    fr: 'légendes', pt: 'legendas', ru: 'подписи', zh: '字幕',
    ar: 'التعليقات', ja: 'キャプション', ko: '자막',
  },
  NsfwButton: {
    en: 'nsfw', it: 'nsfw', de: 'nsfw', es: 'nsfw', fr: 'nsfw',
    pt: 'nsfw', ru: 'nsfw', zh: 'nsfw', ar: 'nsfw', ja: 'nsfw', ko: 'nsfw',
  },
  ExtractorsButton: {
    en: 'extractors', it: 'estrattori', de: 'extraktoren', es: 'extractores',
    fr: 'extracteurs', pt: 'extratores', ru: 'экстракторы', zh: '提取器',
    ar: 'المستخلصات', ja: 'エクストラクター', ko: '추출기',
  },
  DisabledExtractorsSettingsMessage: {
    en: 'select which extractors should be disabled',
    it: 'seleziona quali estrattori disabilitare',
    de: 'wähle, welche Extraktoren deaktiviert werden sollen',
    es: 'selecciona qué extractores deben deshabilitarse',
    fr: 'sélectionne quels extracteurs doivent être désactivés',
    pt: 'selecione quais extratores devem ser desativados',
    ru: 'выберите, какие экстракторы следует отключить',
    zh: '选择应禁用哪些提取器', ar: 'اختر المستخلصات التي يجب تعطيلها',
    ja: '無効にするエクストラクターを選択してください',
    ko: '비활성화할 추출기를 선택하세요',
  },
  DeleteLinksButton: {
    en: 'links', it: 'link', de: 'links', es: 'enlaces', fr: 'liens',
    pt: 'links', ru: 'ссылки', zh: '链接', ar: 'الروابط', ja: 'リンク', ko: '링크',
  },
  DeleteLinksSettingsMessage: {
    en: 'when enabled, deletes the original message after processing the link',
    it: 'se abilitato, elimina il messaggio originale dopo aver elaborato il link',
    de: 'wenn aktiviert, löscht die ursprüngliche Nachricht nach der Verarbeitung des Links',
    es: 'cuando está habilitado, elimina el mensaje original después de procesar el enlace',
    fr: 'si activé, supprime le message original après traitement du lien',
    pt: 'quando ativado, exclui a mensagem original após processar o link',
    ru: 'если включено, удаляет исходное сообщение после обработки ссылки',
    zh: '启用后，处理链接后删除原始消息', ar: 'عند التفعيل، يحذف الرسالة الأصلية بعد معالجة الرابط',
    ja: '有効にすると、リンク処理後に元のメッセージが削除されます',
    ko: '활성화하면 링크 처리 후 원본 메시지가 삭제됩니다',
  },
  SupportedExtractorsMessage: {
    en: 'list of supported extractors by the bot',
    it: 'lista degli estrattori supportati dal bot',
    de: 'liste der vom Bot unterstützten Extraktoren',
    es: 'lista de extractores compatibles con el bot',
    fr: 'liste des extracteurs pris en charge par le bot',
    pt: 'lista de extratores suportados pelo bot',
    ru: 'список экстракторов, поддерживаемых ботом',
    zh: '机器人支持的提取器列表', ar: 'قائمة المستخلصات المدعومة من البوت',
    ja: 'ボットがサポートするエクストラクターの一覧',
    ko: '봇이 지원하는 추출기 목록',
  },
  EnabledButton: {
    en: 'enabled', it: 'abilitato', de: 'aktiviert', es: 'habilitado',
    fr: 'activé', pt: 'ativado', ru: 'включено', zh: '已启用',
    ar: 'مفعّل', ja: '有効', ko: '활성화됨',
  },
  DisabledButton: {
    en: 'disabled', it: 'disabilitato', de: 'deaktiviert', es: 'deshabilitado',
    fr: 'désactivé', pt: 'desativado', ru: 'отключено', zh: '已禁用',
    ar: 'معطّل', ja: '無効', ko: '비활성화됨',
  },
  ErrorInstagramStoriesUnsupported: {
    en: 'instagram stories cannot be downloaded by this bot. try igram.site or a dedicated app on android/ios',
    it: 'le storie instagram non possono essere scaricate da questo bot. prova igram.site oppure un\'app dedicata su android/ios',
    de: 'instagram-stories können von diesem bot nicht heruntergeladen werden. versuche igram.site oder eine dedizierte app auf android/ios',
    es: 'este bot no puede descargar las historias de instagram. prueba igram.site o una aplicación dedicada en android/ios',
    fr: 'les stories instagram ne peuvent pas être téléchargées par ce bot. essayez igram.site ou une application dédiée sur android/ios',
    pt: 'as histórias do instagram não podem ser baixadas por este bot. tente igram.site ou um aplicativo dedicado no android/ios',
    ru: 'истории instagram не могут быть загружены этим ботом. попробуйте igram.site или специальное приложение на android/ios',
    zh: '此机器人无法下载 instagram 限时动态。请尝试 igram.site 或 android/ios 上的专用应用',
    ar: 'لا يمكن لهذا البوت تنزيل قصص انستغرام. جرّب igram.site أو تطبيقاً مخصصاً على أندرويد/ios',
    ja: 'このボットではinstagramのストーリーをダウンロードできません。igram.siteかandroid/ios専用アプリをお試しください',
    ko: '이 봇으로는 인스타그램 스토리를 다운로드할 수 없습니다. igram.site 또는 android/ios 전용 앱을 사용하세요',
  },
  ErrorUnavailable: {
    en: 'this content is unavailable',
    it: 'questo contenuto non è disponibile',
    de: 'dieser inhalt ist nicht verfügbar',
    es: 'este contenido no está disponible',
    fr: 'ce contenu n\'est pas disponible',
    pt: 'este conteúdo não está disponível',
    ru: 'этот контент недоступен',
    zh: '该内容不可用',
    ar: 'هذا المحتوى غير متاح',
    ja: 'このコンテンツは利用できません',
    ko: '이 콘텐츠는 사용할 수 없습니다',
  },
  ErrorTimeout: {
    en: 'timeout error when downloading. try again later',
    it: 'errore di timeout durante il download. riprova più tardi',
    de: 'zeitüberschreitung beim herunterladen. versuche es später erneut',
    es: 'error de tiempo de espera al descargar. inténtalo más tarde',
    fr: 'erreur de délai lors du téléchargement. réessayez plus tard',
    pt: 'erro de tempo limite ao baixar. tente novamente mais tarde',
    ru: 'ошибка тайм-аута при загрузке. повторите попытку позже',
    zh: '下载超时，请稍后再试',
    ar: 'انتهت مهلة التنزيل. حاول مرة أخرى لاحقاً',
    ja: 'ダウンロード中にタイムアウトしました。後でもう一度お試しください',
    ko: '다운로드 시간이 초과되었습니다. 나중에 다시 시도해 주세요',
  },
  ErrorUnsupportedImageFormat: {
    en: 'unsupported image format',
    it: 'formato immagine non supportato',
    de: 'nicht unterstütztes bildformat',
    es: 'formato de imagen no compatible',
    fr: 'format d\'image non pris en charge',
    pt: 'formato de imagem não suportado',
    ru: 'неподдерживаемый формат изображения',
    zh: '不支持的图像格式',
    ar: 'تنسيق الصورة غير مدعوم',
    ja: 'サポートされていない画像形式です',
    ko: '지원되지 않는 이미지 형식입니다',
  },
  ErrorMediaAlbumLimitExceeded: {
    en: 'media album limit exceeds the maximum allowed for this group',
    it: 'il limite dell\'album multimediale supera il massimo consentito per questo gruppo',
    de: 'das medienalbum-limit überschreitet das für diese gruppe erlaubte maximum',
    es: 'el límite del álbum multimedia supera el máximo permitido para este grupo',
    fr: 'la limite de l\'album multimédia dépasse le maximum autorisé pour ce groupe',
    pt: 'o limite do álbum de mídia excede o máximo permitido para este grupo',
    ru: 'лимит медиаальбома превышает максимально допустимый для этой группы',
    zh: '媒体相册数量超过此群组允许的最大值',
    ar: 'حد ألبوم الوسائط يتجاوز الحد الأقصى المسموح به لهذه المجموعة',
    ja: 'メディアアルバムの上限がこのグループの最大許容数を超えています',
    ko: '미디어 앨범 한도가 이 그룹의 최대 허용치를 초과했습니다',
  },
  ErrorMediaAlbumGlobalLimitExceeded: {
    en: 'media album limit exceeds the maximum allowed for this instance',
    it: 'il limite dell\'album multimediale supera il massimo consentito per questa istanza',
    de: 'das medienalbum-limit überschreitet das für diese instanz erlaubte maximum',
    es: 'el límite del álbum multimedia supera el máximo permitido para esta instancia',
    fr: 'la limite de l\'album multimédia dépasse le maximum autorisé pour cette instance',
    pt: 'o limite do álbum de mídia excede o máximo permitido para esta instância',
    ru: 'лимит медиаальбома превышает максимально допустимый для этого экземпляра',
    zh: '媒体相册数量超过此实例允许的最大值',
    ar: 'حد ألبوم الوسائط يتجاوز الحد الأقصى المسموح به لهذا النظام',
    ja: 'メディアアルバムの上限がこのインスタンスの最大許容数を超えています',
    ko: '미디어 앨범 한도가 이 인스턴스의 최대 허용치를 초과했습니다',
  },
  ErrorGeoRestrictedContent: {
    en: 'this tiktok video is not available in your region. try snaptik.app',
    it: 'questo video tiktok non è disponibile nella tua regione. prova snaptik.app',
    de: 'dieses tiktok-video ist in deiner region nicht verfügbar. versuche snaptik.app',
    es: 'este vídeo de tiktok no está disponible en tu región. prueba snaptik.app',
    fr: 'cette vidéo tiktok n\'est pas disponible dans ta région. essayez snaptik.app',
    pt: 'este vídeo do tiktok não está disponível na sua região. tente snaptik.app',
    ru: 'это видео tiktok недоступно в вашем регионе. попробуйте snaptik.app',
    zh: '该 tiktok 视频在你的地区不可用。请尝试 snaptik.app',
    ar: 'هذا الفيديو من tiktok غير متاح في منطقتك. جرّب snaptik.app',
    ja: 'このtiktok動画はお住まいの地域では利用できません。snaptik.appをお試しください',
    ko: '이 tiktok 동영상은 해당 지역에서 이용할 수 없습니다. snaptik.app을 사용해 보세요',
  },
  ErrorNSFWNotAllowed: {
    en: 'this content is nsfw and cannot be downloaded here',
    it: 'questo contenuto è nsfw e non può essere scaricato qui',
    de: 'dieser inhalt ist nsfw und kann hier nicht heruntergeladen werden',
    es: 'este contenido es nsfw y no se puede descargar aquí',
    fr: 'ce contenu est nsfw et ne peut pas être téléchargé ici',
    pt: 'este conteúdo é nsfw e não pode ser baixado aqui',
    ru: 'этот контент nsfw и не может быть загружен здесь',
    zh: '该内容为 nsfw，无法在此处下载',
    ar: 'هذا المحتوى غير لائق ولا يمكن تنزيله هنا',
    ja: 'このコンテンツは NSFW のため、ここではダウンロードできません',
    ko: '이 콘텐츠는 nsfw로 여기서 다운로드할 수 없습니다',
  },
  ErrorInlineMediaAlbum: {
    en: 'media albums not supported in inline mode',
    it: 'gli album multimediali non sono supportati in modalità inline',
    de: 'medienalben werden im inline-modus nicht unterstützt',
    es: 'los álbumes multimedia no están disponibles en modo inline',
    fr: 'les albums multimédias ne sont pas pris en charge en mode inline',
    pt: 'álbuns de mídia não são suportados no modo inline',
    ru: 'медиаальбомы не поддерживаются в инлайн-режиме',
    zh: '内联模式不支持媒体相册',
    ar: 'ألبومات الوسائط غير مدعومة في الوضع المضمّن',
    ja: 'インラインモードではメディアアルバムはサポートされていません',
    ko: '인라인 모드에서는 미디어 앨범이 지원되지 않습니다',
  },
  ErrorAuthenticationNeeded: {
    en: 'this instance is not authenticated with this service',
    it: 'questa istanza non è autenticata con questo servizio',
    de: 'diese instanz ist nicht bei diesem dienst authentifiziert',
    es: 'esta instancia no está autenticada con este servicio',
    fr: 'cette instance n\'est pas authentifiée avec ce service',
    pt: 'esta instância não está autenticada com este serviço',
    ru: 'этот экземпляр не аутентифицирован в данном сервисе',
    zh: '此实例未通过该服务的身份验证',
    ar: 'هذا النظام غير مصادق عليه مع هذه الخدمة',
    ja: 'このインスタンスはこのサービスで認証されていません',
    ko: '이 인스턴스는 이 서비스에 인증되지 않았습니다',
  },
  ErrorFileTooLarge: {
    en: 'this file is too large',
    it: 'questo file è troppo grande',
    de: 'diese datei ist zu groß',
    es: 'este archivo es demasiado grande',
    fr: 'ce fichier est trop volumineux',
    pt: 'este arquivo é muito grande',
    ru: 'этот файл слишком большой',
    zh: '该文件太大',
    ar: 'هذا الملف كبير جداً',
    ja: 'このファイルは大きすぎます',
    ko: '이 파일은 너무 큽니다',
  },
  ErrorTelegramFileTooLarge: {
    en: 'this file is too large for telegram',
    it: 'questo file è troppo grande per telegram',
    de: 'diese datei ist zu groß für telegram',
    es: 'este archivo es demasiado grande para telegram',
    fr: 'ce fichier est trop volumineux pour telegram',
    pt: 'este arquivo é muito grande para o telegram',
    ru: 'этот файл слишком большой для telegram',
    zh: '该文件对于 telegram 来说太大了',
    ar: 'هذا الملف كبير جداً بالنسبة لتيليجرام',
    ja: 'このファイルは Telegram には大きすぎます',
    ko: '이 파일은 텔레그램에 너무 큽니다',
  },
  ErrorDurationTooLong: {
    en: 'this video is too long',
    it: 'questo video è troppo lungo',
    de: 'dieses video ist zu lang',
    es: 'este vídeo es demasiado largo',
    fr: 'cette vidéo est trop longue',
    pt: 'este vídeo é muito longo',
    ru: 'это видео слишком длинное',
    zh: '该视频时长过长',
    ar: 'هذا الفيديو طويل جداً',
    ja: 'この動画は長すぎます',
    ko: '이 동영상은 너무 깁니다',
  },
  ErrorPaidContent: {
    en: 'this content requires a subscription',
    it: 'questo contenuto richiede un abbonamento',
    de: 'für diesen inhalt ist ein abonnement erforderlich',
    es: 'este contenido requiere una suscripción',
    fr: 'ce contenu nécessite un abonnement',
    pt: 'este conteúdo requer uma assinatura',
    ru: 'этот контент требует подписки',
    zh: '该内容需要订阅',
    ar: 'هذا المحتوى يتطلب اشتراكاً',
    ja: 'このコンテンツはサブスクリプションが必要です',
    ko: '이 콘텐츠는 구독이 필요합니다',
  },
  ErrorAgeRestricted: {
    en: 'this content is age-restricted',
    it: 'questo contenuto ha una restrizione di età',
    de: 'dieser inhalt hat eine altersfreigabe',
    es: 'este contenido tiene restricción de edad',
    fr: 'ce contenu est soumis à une restriction d\'âge',
    pt: 'este conteúdo tem restrição de idade',
    ru: 'этот контент имеет возрастное ограничение',
    zh: '该内容有年龄限制',
    ar: 'هذا المحتوى مقيد بالعمر',
    ja: 'このコンテンツは年齢制限があります',
    ko: '이 콘텐츠는 연령 제한이 있습니다',
  },
  ErrorPermissionDenied: {
    en: 'the bot lacks permissions to send media here',
    it: 'il bot non ha i permessi per inviare media qui',
    de: 'der bot hat keine berechtigung, medien hier zu senden',
    es: 'el bot no tiene permisos para enviar medios aquí',
    fr: 'le bot n\'a pas les autorisations pour envoyer des médias ici',
    pt: 'o bot não tem permissões para enviar mídia aqui',
    ru: 'у бота нет прав для отправки медиафайлов здесь',
    zh: '机器人没有在此发送媒体的权限',
    ar: 'ليس لدى البوت صلاحيات لإرسال الوسائط هنا',
    ja: 'ボットにはここでメディアを送信する権限がありません',
    ko: '봇이 여기에 미디어를 보낼 권한이 없습니다',
  },
  ErrorResolutionFailed: {
    en: 'failed to resolve url',
    it: 'impossibile risolvere l\'url',
    de: 'url konnte nicht aufgelöst werden',
    es: 'no se pudo resolver la url',
    fr: 'impossible de résoudre l\'url',
    pt: 'falha ao resolver o url',
    ru: 'не удалось обработать url',
    zh: '无法解析链接',
    ar: 'فشل في معالجة الرابط',
    ja: 'URLを解決できませんでした',
    ko: 'URL을 확인할 수 없습니다',
  },
};

function buildResources(msgs: Messages): Record<string, { translation: Record<string, string> }> {
  const resources: Record<string, { translation: Record<string, string> }> = {};
  for (const [key, translations] of Object.entries(msgs)) {
    for (const [lang, value] of Object.entries(translations)) {
      if (!value) continue;
      if (!resources[lang]) resources[lang] = { translation: {} };
      resources[lang].translation[key] = value;
    }
  }
  return resources;
}

const i18n = i18next.createInstance();
i18n.init({
  lng: 'en',
  fallbackLng: 'en',
  resources: buildResources(messages),
  interpolation: { escapeValue: false },
});

export function t(messageId: string, lang: string = 'en', data: Record<string, string> = {}): string {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return String((i18n.t as any)(messageId, { lng: lang, ...data }));
}

export function localizer(lang: string = 'en'): { t: (messageId: string, data?: Record<string, string>) => string } {
  return {
    t: (messageId: string, data: Record<string, string> = {}) => t(messageId, lang, data),
  };
}
